name: mockio
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  event_bus: ^2.0.0
  mocktail: ^0.3.0
  mqtt_client: ^9.8.0
  typed_data: ^1.3.1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.23.1



