name: mockio
description: Repository for experimenting with io mocking in Dart
version: 0.1.0
repository: https://github.com/shamblett/mockio

publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  mocktail: ^0.3.0
  mqtt_client: ^9.8.0
  typed_data: ^1.3.1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.23.1



