name: mockio
description: Repository for experimenting with io mocking in Dart
version: 0.2.0
repository: https://github.com/shamblett/mockio

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mocktail: ^0.3.0
  mqtt_client: ^9.8.1
  typed_data: ^1.3.2


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2



